namespace Oaf.Frontend.Compiler.Lexer;

public enum TokenKind
{
    BadToken,
    EndOfFileToken,

    IdentifierToken,
    NumberToken,
    StringToken,
    CharToken,

    OpenParenToken,
    CloseParenToken,
    OpenBracketToken,
    CloseBracketToken,
    OpenBraceToken,
    CloseBraceToken,
    CommaToken,
    DotToken,
    ColonToken,

    SemicolonToken,

    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    PercentToken,
    CaretToken,
    RootToken,
    TildeToken,

    AmpersandToken,
    PipeToken,
    DoubleAmpersandToken,
    DoublePipeToken,
    BangToken,
    BangPipeToken,
    BangAmpersandToken,
    CaretAmpersandToken,

    EqualsToken,
    PlusEqualsToken,
    MinusEqualsToken,
    StarEqualsToken,
    SlashEqualsToken,

    EqualsEqualsToken,
    BangEqualsToken,
    LessToken,
    LessOrEqualsToken,
    GreaterToken,
    GreaterOrEqualsToken,
    ShiftLeftToken,
    ShiftRightToken,
    UnsignedShiftLeftToken,
    UnsignedShiftRightToken,

    ArrowToken,
    FatArrowToken,
    BindToken,

    IfKeyword,
    LoopKeyword,
    ParalloopKeyword,
    ReturnKeyword,
    ThrowKeyword,
    CatchKeyword,
    ClassKeyword,
    PublicKeyword,
    FluxKeyword,
    EnumKeyword,
    StructKeyword,
    MatchKeyword,
    ActorKeyword,
    GcKeyword,
    BaseKeyword,
    RecurseKeyword,
    BreakKeyword,
    ContinueKeyword,
    WhenKeyword,
    ModuleKeyword,
    ImportKeyword,
    TrueKeyword,
    FalseKeyword
}
